# -*- coding: utf-8 -*-
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import PyQt5

import components.lyric_window_view.source


class Ui_LyricsWindow(object):
    def setupUi(self, LyricsWindow):
        if not LyricsWindow.objectName():
            LyricsWindow.setObjectName(u"LyricsWindow")
        LyricsWindow.resize(803, 141)
        LyricsWindow.setMinimumSize(QSize(552, 106))
        LyricsWindow.setMaximumSize(QSize(1920, 308))
        font = QFont()
        font.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")  # 微软雅黑
        font.setPointSize(20)
        LyricsWindow.setFont(font)
        LyricsWindow.setStyleSheet(u"*\n"
                                   "{\n"
                                   "border:none;\n"
                                   "}")
        self.main_gridLayout = QGridLayout(LyricsWindow)
        self.main_gridLayout.setSpacing(0)
        self.main_gridLayout.setObjectName(u"main_gridLayout")
        self.main_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.background_frame = QFrame(LyricsWindow)
        self.background_frame.setObjectName(u"background_frame")
        self.background_frame.setFrameShape(QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QFrame.Raised)
        self.background_gridLayout = QGridLayout(self.background_frame)
        self.background_gridLayout.setSpacing(0)
        self.background_gridLayout.setObjectName(u"background_gridLayout")
        self.background_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.lyrics_frame1 = QFrame(self.background_frame)
        self.lyrics_frame1.setObjectName(u"lyrics_frame1")
        self.lyrics_frame1.setFont(font)
        self.lyrics_frame1.setCursor(QCursor(Qt.ArrowCursor))
        self.lyrics_frame1.setFrameShape(QFrame.StyledPanel)
        self.lyrics_frame1.setFrameShadow(QFrame.Raised)
        self.lyrics_gridLayout1 = QGridLayout(self.lyrics_frame1)
        self.lyrics_gridLayout1.setSpacing(0)
        self.lyrics_gridLayout1.setObjectName(u"lyrics_gridLayout1")
        self.lyrics_gridLayout1.setContentsMargins(0, 0, 0, 0)

        self.background_gridLayout.addWidget(self.lyrics_frame1, 1, 0, 1, 1)

        self.lyrics_frame2 = QFrame(self.background_frame)
        self.lyrics_frame2.setObjectName(u"lyrics_frame2")
        self.lyrics_frame2.setFont(font)
        self.lyrics_frame2.setCursor(QCursor(Qt.ArrowCursor))
        self.lyrics_frame2.setFrameShape(QFrame.StyledPanel)
        self.lyrics_frame2.setFrameShadow(QFrame.Raised)
        self.lyrics_gridLayout2 = QGridLayout(self.lyrics_frame2)
        self.lyrics_gridLayout2.setSpacing(0)
        self.lyrics_gridLayout2.setObjectName(u"lyrics_gridLayout2")
        self.lyrics_gridLayout2.setContentsMargins(0, 0, 0, 0)

        self.background_gridLayout.addWidget(self.lyrics_frame2, 2, 0, 1, 1)

        self.buttons_frame = QFrame(self.background_frame)
        self.buttons_frame.setObjectName(u"buttons_frame")
        self.buttons_frame.setMinimumSize(QSize(552, 30))
        self.buttons_frame.setMaximumSize(QSize(1920, 30))
        self.buttons_frame.setFrameShape(QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QFrame.Raised)
        self.buttons_horizontalLayout = QHBoxLayout(self.buttons_frame)
        self.buttons_horizontalLayout.setObjectName(u"buttons_horizontalLayout")
        self.horizontalSpacer_left = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.buttons_horizontalLayout.addItem(self.horizontalSpacer_left)

        self.calibrate_frame = QFrame(self.buttons_frame)
        self.calibrate_frame.setObjectName(u"calibrate_frame")
        self.calibrate_frame.setMinimumSize(QSize(20, 20))
        self.calibrate_frame.setMaximumSize(QSize(20, 20))
        self.calibrate_frame.setFrameShape(QFrame.StyledPanel)
        self.calibrate_frame.setFrameShadow(QFrame.Raised)
        self.calibrate_gridLayout = QGridLayout(self.calibrate_frame)
        self.calibrate_gridLayout.setSpacing(0)
        self.calibrate_gridLayout.setObjectName(u"calibrate_gridLayout")
        self.calibrate_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrate_button = QPushButton(self.calibrate_frame)
        self.calibrate_button.setObjectName(u"calibrate_button")
        self.calibrate_button.setMinimumSize(QSize(20, 20))
        self.calibrate_button.setMaximumSize(QSize(20, 20))
        font1 = QFont()
        font1.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        self.calibrate_button.setFont(font1)
        self.calibrate_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u":/pic/images/calibrate.png", QSize(), QIcon.Normal, QIcon.Off)
        self.calibrate_button.setIcon(icon)

        self.calibrate_gridLayout.addWidget(self.calibrate_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.calibrate_frame)

        self.account_frame = QFrame(self.buttons_frame)
        self.account_frame.setObjectName(u"account_frame")
        self.account_frame.setMinimumSize(QSize(20, 20))
        self.account_frame.setMaximumSize(QSize(20, 20))
        self.account_frame.setFrameShape(QFrame.StyledPanel)
        self.account_frame.setFrameShadow(QFrame.Raised)
        self.account_gridLayout = QGridLayout(self.account_frame)
        self.account_gridLayout.setSpacing(0)
        self.account_gridLayout.setObjectName(u"account_gridLayout")
        self.account_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.account_button = QPushButton(self.account_frame)
        self.account_button.setObjectName(u"account_button")
        self.account_button.setMinimumSize(QSize(20, 20))
        self.account_button.setMaximumSize(QSize(20, 20))
        self.account_button.setFont(font1)
        self.account_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/pic/images/account.png", QSize(), QIcon.Normal, QIcon.Off)
        self.account_button.setIcon(icon1)

        self.account_gridLayout.addWidget(self.account_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.account_frame)

        self.last_frame = QFrame(self.buttons_frame)
        self.last_frame.setObjectName(u"last_frame")
        self.last_frame.setMinimumSize(QSize(20, 20))
        self.last_frame.setMaximumSize(QSize(20, 20))
        self.last_frame.setFrameShape(QFrame.StyledPanel)
        self.last_frame.setFrameShadow(QFrame.Raised)
        self.last_gridLayout = QGridLayout(self.last_frame)
        self.last_gridLayout.setSpacing(0)
        self.last_gridLayout.setObjectName(u"last_gridLayout")
        self.last_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.last_button = QPushButton(self.last_frame)
        self.last_button.setObjectName(u"last_button")
        self.last_button.setMinimumSize(QSize(20, 20))
        self.last_button.setMaximumSize(QSize(20, 20))
        self.last_button.setFont(font1)
        self.last_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/pic/images/last.png", QSize(), QIcon.Normal, QIcon.Off)
        self.last_button.setIcon(icon2)

        self.last_gridLayout.addWidget(self.last_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.last_frame)

        self.pause_frame = QFrame(self.buttons_frame)
        self.pause_frame.setObjectName(u"pause_frame")
        self.pause_frame.setMinimumSize(QSize(20, 20))
        self.pause_frame.setMaximumSize(QSize(20, 20))
        self.pause_frame.setFrameShape(QFrame.StyledPanel)
        self.pause_frame.setFrameShadow(QFrame.Raised)
        self.pause_gridLayout = QGridLayout(self.pause_frame)
        self.pause_gridLayout.setSpacing(0)
        self.pause_gridLayout.setObjectName(u"pause_gridLayout")
        self.pause_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pause_button = QPushButton(self.pause_frame)
        self.pause_button.setObjectName(u"pause_button")
        self.pause_button.setMinimumSize(QSize(20, 20))
        self.pause_button.setMaximumSize(QSize(20, 20))
        self.pause_button.setFont(font1)
        self.pause_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/pic/images/continue.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pause_button.setIcon(icon3)

        self.pause_gridLayout.addWidget(self.pause_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.pause_frame)

        self.next_frame = QFrame(self.buttons_frame)
        self.next_frame.setObjectName(u"next_frame")
        self.next_frame.setMinimumSize(QSize(20, 20))
        self.next_frame.setMaximumSize(QSize(20, 20))
        self.next_frame.setFrameShape(QFrame.StyledPanel)
        self.next_frame.setFrameShadow(QFrame.Raised)
        self.next_gridLayout = QGridLayout(self.next_frame)
        self.next_gridLayout.setSpacing(0)
        self.next_gridLayout.setObjectName(u"next_gridLayout")
        self.next_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.next_button = QPushButton(self.next_frame)
        self.next_button.setObjectName(u"next_button")
        self.next_button.setMinimumSize(QSize(20, 20))
        self.next_button.setMaximumSize(QSize(20, 20))
        self.next_button.setFont(font1)
        self.next_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/pic/images/next.png", QSize(), QIcon.Normal, QIcon.Off)
        self.next_button.setIcon(icon4)

        self.next_gridLayout.addWidget(self.next_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.next_frame)

        self.settings_frame = QFrame(self.buttons_frame)
        self.settings_frame.setObjectName(u"settings_frame")
        self.settings_frame.setMinimumSize(QSize(20, 20))
        self.settings_frame.setMaximumSize(QSize(20, 20))
        self.settings_frame.setFrameShape(QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QFrame.Raised)
        self.settings_gridLayout = QGridLayout(self.settings_frame)
        self.settings_gridLayout.setSpacing(0)
        self.settings_gridLayout.setObjectName(u"settings_gridLayout")
        self.settings_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.settings_button = QPushButton(self.settings_frame)
        self.settings_button.setObjectName(u"settings_button")
        self.settings_button.setMinimumSize(QSize(20, 20))
        self.settings_button.setMaximumSize(QSize(20, 20))
        self.settings_button.setFont(font1)
        self.settings_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/pic/images/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_button.setIcon(icon5)

        self.settings_gridLayout.addWidget(self.settings_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.settings_frame)

        self.lock_frame = QFrame(self.buttons_frame)
        self.lock_frame.setObjectName(u"lock_frame")
        self.lock_frame.setMinimumSize(QSize(20, 20))
        self.lock_frame.setMaximumSize(QSize(20, 20))
        self.lock_frame.setFrameShape(QFrame.StyledPanel)
        self.lock_frame.setFrameShadow(QFrame.Raised)
        self.lock_gridLayout = QGridLayout(self.lock_frame)
        self.lock_gridLayout.setSpacing(0)
        self.lock_gridLayout.setObjectName(u"lock_gridLayout")
        self.lock_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.lock_button = QPushButton(self.lock_frame)
        self.lock_button.setObjectName(u"lock_button")
        self.lock_button.setMinimumSize(QSize(20, 20))
        self.lock_button.setMaximumSize(QSize(20, 20))
        self.lock_button.setFont(font1)
        self.lock_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/pic/images/lock.png", QSize(), QIcon.Normal, QIcon.Off)
        self.lock_button.setIcon(icon6)

        self.lock_gridLayout.addWidget(self.lock_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.lock_frame)

        self.translate_frame = QFrame(self.buttons_frame)
        self.translate_frame.setObjectName(u"translate_frame")
        self.translate_frame.setMinimumSize(QSize(20, 20))
        self.translate_frame.setMaximumSize(QSize(20, 20))
        self.translate_frame.setFrameShape(QFrame.StyledPanel)
        self.translate_frame.setFrameShadow(QFrame.Raised)
        self.translate_gridLayout = QGridLayout(self.translate_frame)
        self.translate_gridLayout.setSpacing(0)
        self.translate_gridLayout.setObjectName(u"translate_gridLayout")
        self.translate_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.translate_button = QPushButton(self.translate_frame)
        self.translate_button.setObjectName(u"translate_button")
        self.translate_button.setMinimumSize(QSize(20, 20))
        self.translate_button.setMaximumSize(QSize(20, 20))
        self.translate_button.setFont(font1)
        self.translate_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/pic/images/translate.png", QSize(), QIcon.Normal, QIcon.Off)
        self.translate_button.setIcon(icon7)

        self.translate_gridLayout.addWidget(self.translate_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.translate_frame)

        self.offsetdown_frame = QFrame(self.buttons_frame)
        self.offsetdown_frame.setObjectName(u"offsetdown_frame")
        self.offsetdown_frame.setMinimumSize(QSize(20, 20))
        self.offsetdown_frame.setMaximumSize(QSize(20, 20))
        self.offsetdown_frame.setFrameShape(QFrame.StyledPanel)
        self.offsetdown_frame.setFrameShadow(QFrame.Raised)
        self.offsetdown_gridLayout = QGridLayout(self.offsetdown_frame)
        self.offsetdown_gridLayout.setSpacing(0)
        self.offsetdown_gridLayout.setObjectName(u"offsetdown_gridLayout")
        self.offsetdown_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.offsetdown_button = QPushButton(self.offsetdown_frame)
        self.offsetdown_button.setObjectName(u"offsetdown_button")
        self.offsetdown_button.setMinimumSize(QSize(20, 20))
        self.offsetdown_button.setMaximumSize(QSize(20, 20))
        self.offsetdown_button.setFont(font1)
        self.offsetdown_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/pic/images/setoffdown.png", QSize(), QIcon.Normal, QIcon.Off)
        self.offsetdown_button.setIcon(icon8)

        self.offsetdown_gridLayout.addWidget(self.offsetdown_button, 0, 1, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.offsetdown_frame)

        self.offsetup_frame = QFrame(self.buttons_frame)
        self.offsetup_frame.setObjectName(u"offsetup_frame")
        self.offsetup_frame.setMinimumSize(QSize(20, 20))
        self.offsetup_frame.setMaximumSize(QSize(20, 20))
        self.offsetup_frame.setFrameShape(QFrame.StyledPanel)
        self.offsetup_frame.setFrameShadow(QFrame.Raised)
        self.offsetup_gridLayout = QGridLayout(self.offsetup_frame)
        self.offsetup_gridLayout.setSpacing(0)
        self.offsetup_gridLayout.setObjectName(u"offsetup_gridLayout")
        self.offsetup_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.offsetup_button = QPushButton(self.offsetup_frame)
        self.offsetup_button.setObjectName(u"offsetup_button")
        self.offsetup_button.setMinimumSize(QSize(20, 20))
        self.offsetup_button.setMaximumSize(QSize(20, 20))
        self.offsetup_button.setFont(font1)
        self.offsetup_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/pic/images/setoffup.png", QSize(), QIcon.Normal, QIcon.Off)
        self.offsetup_button.setIcon(icon9)

        self.offsetup_gridLayout.addWidget(self.offsetup_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.offsetup_frame)

        self.close_frame = QFrame(self.buttons_frame)
        self.close_frame.setObjectName(u"close_frame")
        self.close_frame.setMinimumSize(QSize(20, 20))
        self.close_frame.setMaximumSize(QSize(20, 20))
        self.close_frame.setFrameShape(QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QFrame.Raised)
        self.close_gridLayout = QGridLayout(self.close_frame)
        self.close_gridLayout.setSpacing(0)
        self.close_gridLayout.setObjectName(u"close_gridLayout")
        self.close_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.close_button = QPushButton(self.close_frame)
        self.close_button.setObjectName(u"close_button")
        self.close_button.setMinimumSize(QSize(20, 20))
        self.close_button.setMaximumSize(QSize(20, 20))
        self.close_button.setFont(font1)
        self.close_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u":/pic/images/close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.close_button.setIcon(icon10)

        self.close_gridLayout.addWidget(self.close_button, 0, 0, 1, 1)

        self.buttons_horizontalLayout.addWidget(self.close_frame)

        self.horizontalSpacer_right = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.buttons_horizontalLayout.addItem(self.horizontalSpacer_right)

        self.background_gridLayout.addWidget(self.buttons_frame, 0, 0, 1, 1)

        self.main_gridLayout.addWidget(self.background_frame, 0, 0, 1, 1)

        self.retranslateUi(LyricsWindow)

        QMetaObject.connectSlotsByName(LyricsWindow)

    # setupUi

    def retranslateUi(self, LyricsWindow):
        LyricsWindow.setWindowTitle(QCoreApplication.translate("LyricsWindow", u"Form", None))
        # if QT_CONFIG(tooltip)
        self.calibrate_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u6821\u51c6\u6b4c\u8bcd", None))
        # endif // QT_CONFIG(tooltip)
        self.calibrate_button.setText("")
        # if QT_CONFIG(tooltip)
        self.account_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u7528\u6237\u6388\u6743", None))
        # endif // QT_CONFIG(tooltip)
        self.account_button.setText("")
        # if QT_CONFIG(tooltip)
        self.last_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u4e0a\u4e00\u9996", None))
        # endif // QT_CONFIG(tooltip)
        self.last_button.setText("")
        # if QT_CONFIG(tooltip)
        self.pause_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u64ad\u653e/\u6682\u505c", None))
        # endif // QT_CONFIG(tooltip)
        self.pause_button.setText("")
        # if QT_CONFIG(tooltip)
        self.next_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u4e0b\u4e00\u9996", None))
        # endif // QT_CONFIG(tooltip)
        self.next_button.setText("")
        # if QT_CONFIG(tooltip)
        self.settings_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u8bbe\u7f6e", None))
        # endif // QT_CONFIG(tooltip)
        self.settings_button.setText("")
        # if QT_CONFIG(tooltip)
        self.lock_button.setToolTip(
            QCoreApplication.translate("LyricsWindow", u"\u9501\u5b9a\u684c\u9762\u6b4c\u8bcd", None))
        # endif // QT_CONFIG(tooltip)
        self.lock_button.setText("")
        # if QT_CONFIG(tooltip)
        self.translate_button.setToolTip(QCoreApplication.translate("LyricsWindow", u"\u5207\u6362\u6b4c\u8bcd", None))
        # endif // QT_CONFIG(tooltip)
        self.translate_button.setText("")
        # if QT_CONFIG(tooltip)
        self.offsetdown_button.setToolTip(
            QCoreApplication.translate("LyricsWindow", u"\u6b4c\u8bcd\u540e\u90000.5s", None))
        # endif // QT_CONFIG(tooltip)
        self.offsetdown_button.setText("")
        # if QT_CONFIG(tooltip)
        self.offsetup_button.setToolTip(
            QCoreApplication.translate("LyricsWindow", u"\u6b4c\u8bcd\u524d\u8fdb0.5s", None))
        # endif // QT_CONFIG(tooltip)
        self.offsetup_button.setText("")
        # if QT_CONFIG(tooltip)
        self.close_button.setToolTip(
            QCoreApplication.translate("LyricsWindow", u"\u5173\u95ed\u684c\u9762\u6b4c\u8bcd", None))
        # endif // QT_CONFIG(tooltip)
        self.close_button.setText("")
    # retranslateUi
